"""Jurisdiction packs.

A pack is a self-contained directory that adapts ThesisLogic to one
jurisdiction (or one court system) without any code change:

    packs/<pack_id>/
        pack.json               manifest: name, jurisdiction, citation patterns,
                                disclaimer, prompt overlays
        practice_areas.json     practice-area registry with routing keywords
        authorities.ndjson      source authority records (one JSON per line)
        authorities.sqlite3     built search index (generated by `pack build`)

Authority record shape (NDJSON), designed so exports from common sources
(CourtListener, state statute scrapes, firm knowledge bases) map onto it:

    {
      "authority_id": "case::123",            # optional; generated if absent
      "authority_type": "case|statute|rule|regulation|ethics_opinion|secondary",
      "citation": "915 S.W.2d 372",
      "title": "Woolridge v. Woolridge",
      "court": "Missouri Court of Appeals",
      "jurisdiction": "Missouri",
      "year": 1996,
      "aliases": ["Woolridge v. Woolridge"],
      "topic_labels": ["family_law"],
      "text": "full text ...",
      "spans": [ {"span_text": "...", "span_type": "holding",
                  "support_eligible": true} ]   # optional; derived if absent
    }
"""

from __future__ import annotations

import json
import re
import sqlite3
from dataclasses import dataclass, field
from pathlib import Path

from .db import connect

AUTHORITY_SCHEMA = """
CREATE TABLE IF NOT EXISTS authorities (
    authority_id TEXT PRIMARY KEY,
    authority_type TEXT NOT NULL,
    citation TEXT NOT NULL,
    normalized_citation TEXT NOT NULL,
    title TEXT NOT NULL,
    court TEXT NOT NULL DEFAULT '',
    jurisdiction TEXT NOT NULL DEFAULT '',
    year INTEGER,
    aliases_json TEXT NOT NULL DEFAULT '[]',
    topic_labels_json TEXT NOT NULL DEFAULT '[]',
    text_excerpt TEXT NOT NULL DEFAULT ''
);
CREATE INDEX IF NOT EXISTS idx_auth_norm ON authorities (normalized_citation);

CREATE VIRTUAL TABLE IF NOT EXISTS authorities_fts USING fts5(
    authority_id UNINDEXED, search_text
);

CREATE TABLE IF NOT EXISTS spans (
    span_id TEXT PRIMARY KEY,
    authority_id TEXT NOT NULL,
    span_text TEXT NOT NULL,
    span_type TEXT NOT NULL,
    support_eligible INTEGER NOT NULL DEFAULT 1,
    position INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_spans_auth ON spans (authority_id);

CREATE TABLE IF NOT EXISTS embeddings (
    authority_id TEXT PRIMARY KEY,
    model_id TEXT NOT NULL,
    vector_json TEXT NOT NULL,
    norm REAL NOT NULL
);
"""

_SENTENCE_SPLIT = re.compile(r"(?<=[.!?])\s+(?=[A-Z“\"(])")

# Heuristic span typing for opinions when the source data has no spans.
_SPAN_TYPE_RULES: list[tuple[str, re.Pattern]] = [
    ("holding", re.compile(r"\b(we hold|we conclude|we affirm|we reverse|held that|holding that|it is held)\b", re.I)),
    ("rule_statement", re.compile(r"\b(must|shall|is required|are required|may not|standard of review|burden of proof|elements? of)\b", re.I)),
    ("procedural", re.compile(r"\b(appeal|remand|motion|petition|trial court|filed|dismissed)\b", re.I)),
]
_CAPTION = re.compile(r"^(IN THE|BEFORE|No\.\s|Case No|Appeal from|Argued|Decided|Filed)", re.I)


def normalize_citation(citation: str) -> str:
    return re.sub(r"\s+", " ", citation.strip().lower())


@dataclass
class PracticeArea:
    id: str
    name: str
    keywords: list[str] = field(default_factory=list)
    description: str = ""
    official_sources: list[dict] = field(default_factory=list)
    priority: int = 100


@dataclass
class Pack:
    pack_id: str
    path: Path
    name: str
    jurisdiction: str
    description: str = ""
    version: str = "1"
    citation_patterns: list[str] = field(default_factory=list)
    disclaimer: str = ""
    prompt_overlay: str = ""
    practice_areas: list[PracticeArea] = field(default_factory=list)
    _citation_regexes: list[re.Pattern] = field(default_factory=list, repr=False)

    @property
    def index_path(self) -> Path:
        return self.path / "authorities.sqlite3"

    def db(self) -> sqlite3.Connection:
        conn = connect(self.index_path)
        conn.executescript(AUTHORITY_SCHEMA)
        return conn

    def citation_regexes(self) -> list[re.Pattern]:
        if not self._citation_regexes:
            self._citation_regexes = [re.compile(p) for p in self.citation_patterns]
        return self._citation_regexes

    def match_practice_areas(self, text: str) -> list[PracticeArea]:
        """Rank practice areas by keyword hits in the given text."""
        lowered = text.lower()
        scored = []
        for pa in self.practice_areas:
            hits = sum(1 for kw in pa.keywords if kw.lower() in lowered)
            if hits:
                scored.append((hits, -pa.priority, pa))
        scored.sort(key=lambda t: (-t[0], t[1]))
        return [pa for _, _, pa in scored]


def load_pack(packs_dir: Path, pack_id: str) -> Pack:
    path = packs_dir / pack_id
    manifest_path = path / "pack.json"
    if not manifest_path.exists():
        raise FileNotFoundError(f"pack manifest not found: {manifest_path}")
    manifest = json.loads(manifest_path.read_text())
    practice_areas: list[PracticeArea] = []
    pa_path = path / "practice_areas.json"
    if pa_path.exists():
        for item in json.loads(pa_path.read_text()).get("practice_areas", []):
            practice_areas.append(PracticeArea(
                id=item.get("id") or re.sub(r"\W+", "_", item.get("name", "")).lower(),
                name=item.get("name", ""),
                keywords=item.get("keywords", []),
                description=item.get("description", ""),
                official_sources=item.get("official_sources", []),
                priority=int(item.get("priority", 100)),
            ))
    return Pack(
        pack_id=pack_id,
        path=path,
        name=manifest.get("name", pack_id),
        jurisdiction=manifest.get("jurisdiction", ""),
        description=manifest.get("description", ""),
        version=str(manifest.get("version", "1")),
        citation_patterns=manifest.get("citation_patterns", []),
        disclaimer=manifest.get("disclaimer", ""),
        prompt_overlay=manifest.get("prompt_overlay", ""),
        practice_areas=practice_areas,
    )


def list_packs(packs_dir: Path) -> list[dict]:
    out = []
    if not packs_dir.exists():
        return out
    for child in sorted(packs_dir.iterdir()):
        if (child / "pack.json").exists():
            try:
                pack = load_pack(packs_dir, child.name)
                built = pack.index_path.exists()
                count = 0
                if built:
                    count = pack.db().execute("SELECT COUNT(*) AS n FROM authorities").fetchone()["n"]
                out.append({
                    "pack_id": pack.pack_id, "name": pack.name,
                    "jurisdiction": pack.jurisdiction, "version": pack.version,
                    "built": built, "authority_count": count,
                    "practice_areas": len(pack.practice_areas),
                })
            except (json.JSONDecodeError, OSError) as exc:
                out.append({"pack_id": child.name, "error": str(exc)})
    return out


def derive_spans(text: str, max_spans: int = 40) -> list[dict]:
    """Segment authority text into typed proposition spans.

    Captions and boilerplate are kept out of the support-eligible pool so the
    proof gate never accepts a case caption as substantive support.
    """
    spans: list[dict] = []
    for idx, sentence in enumerate(_SENTENCE_SPLIT.split(text or "")):
        sentence = sentence.strip()
        if len(sentence) < 40 or len(sentence) > 900:
            continue
        if _CAPTION.match(sentence):
            spans.append({"span_text": sentence[:400], "span_type": "caption", "support_eligible": False, "position": idx})
            continue
        span_type = "discussion"
        for name, pattern in _SPAN_TYPE_RULES:
            if pattern.search(sentence):
                span_type = name
                break
        spans.append({"span_text": sentence, "span_type": span_type, "support_eligible": True, "position": idx})
        if len(spans) >= max_spans:
            break
    return spans


def build_index(pack: Pack, source: Path | None = None, limit: int | None = None,
                progress_every: int = 5000) -> dict:
    """Build (or rebuild) the pack's authority search index from NDJSON."""
    source = source or (pack.path / "authorities.ndjson")
    if not source.exists():
        raise FileNotFoundError(f"authority source not found: {source}")
    if pack.index_path.exists():
        from .db import _connections, _lock  # close stale handle before rebuild
        with _lock:
            conn = _connections.pop(str(pack.index_path), None)
            if conn:
                conn.close()
        pack.index_path.unlink()
    db = pack.db()
    inserted = 0
    span_count = 0
    with source.open() as fh, db:
        for line_no, line in enumerate(fh, start=1):
            line = line.strip()
            if not line:
                continue
            record = json.loads(line)
            authority_id = str(record.get("authority_id") or record.get("opinion_id") or f"auth::{line_no}")
            citation = str(record.get("citation") or "").strip()
            title = str(record.get("title") or "").strip()
            if not citation and not title:
                continue
            text = str(record.get("text") or "")
            aliases = record.get("aliases") or []
            topics = record.get("topic_labels") or []
            year = record.get("year")
            search_text = " ".join(filter(None, [citation, title, " ".join(aliases), " ".join(topics), text[:4000]]))
            db.execute(
                "INSERT OR REPLACE INTO authorities (authority_id, authority_type, citation, "
                "normalized_citation, title, court, jurisdiction, year, aliases_json, "
                "topic_labels_json, text_excerpt) VALUES (?,?,?,?,?,?,?,?,?,?,?)",
                (authority_id, str(record.get("authority_type") or "case"), citation,
                 normalize_citation(citation), title, str(record.get("court") or ""),
                 str(record.get("jurisdiction") or pack.jurisdiction),
                 int(year) if year not in (None, "", "None") else None,
                 json.dumps(aliases), json.dumps(topics), text[:1200]),
            )
            db.execute("INSERT INTO authorities_fts (authority_id, search_text) VALUES (?, ?)",
                       (authority_id, search_text))
            spans = record.get("spans") or derive_spans(text)
            for pos, span in enumerate(spans):
                db.execute(
                    "INSERT OR REPLACE INTO spans (span_id, authority_id, span_text, span_type, "
                    "support_eligible, position) VALUES (?,?,?,?,?,?)",
                    (f"span::{authority_id}::{pos}", authority_id, span["span_text"],
                     span.get("span_type", "discussion"), 1 if span.get("support_eligible", True) else 0,
                     int(span.get("position", pos))),
                )
                span_count += 1
            inserted += 1
            if progress_every and inserted % progress_every == 0:
                print(f"  indexed {inserted} authorities...")
            if limit and inserted >= limit:
                break
    return {"pack_id": pack.pack_id, "authorities": inserted, "spans": span_count,
            "index_path": str(pack.index_path)}


def scaffold_pack(packs_dir: Path, pack_id: str, name: str, jurisdiction: str) -> Path:
    """Create a new pack directory with documented starter files."""
    path = packs_dir / pack_id
    path.mkdir(parents=True, exist_ok=False)
    (path / "pack.json").write_text(json.dumps({
        "name": name,
        "jurisdiction": jurisdiction,
        "description": f"ThesisLogic jurisdiction pack for {jurisdiction}.",
        "version": "1",
        "citation_patterns": [
            r"\b\d{1,4}\s+[A-Z][A-Za-z.]*\.?\s?(?:2d|3d|4th)?\s+\d{1,5}\b",
            r"\b(?:§|[Ss]ection)\s*\d[\w.\-]*\b",
            r"\b[Rr]ule\s+\d[\w.]*\b",
        ],
        "disclaimer": (
            f"AI-assisted work product for {jurisdiction}. Verify every authority before "
            "reliance. This tool does not provide legal advice."),
        "prompt_overlay": (
            f"You are assisting a licensed attorney practicing in {jurisdiction}. "
            "Cite only from the provided authorities."),
    }, indent=2))
    (path / "practice_areas.json").write_text(json.dumps({
        "practice_areas": [
            {
                "id": "general_civil",
                "name": "General Civil Litigation",
                "keywords": ["complaint", "summary judgment", "discovery", "damages"],
                "description": "Replace with your jurisdiction's practice areas.",
                "official_sources": [],
                "priority": 100
            }
        ]
    }, indent=2))
    (path / "authorities.sample.ndjson").write_text(json.dumps({
        "authority_type": "case",
        "citation": "1 Example 100",
        "title": "Example v. Example",
        "court": f"{jurisdiction} Supreme Court",
        "jurisdiction": jurisdiction,
        "year": 2024,
        "aliases": ["Example v. Example"],
        "topic_labels": ["general_civil"],
        "text": "We hold that this sample record demonstrates the authority format. "
                "Replace this file with authorities.ndjson containing your real corpus."
    }) + "\n")
    (path / "README.md").write_text(
        f"# {name}\n\nSee docs/adoption-guide.md in the ThesisLogic repository for how to "
        "populate this pack with your jurisdiction's authorities, practice areas, and firm style.\n")
    return path
